# automatically generated by the FlatBuffers compiler, do not modify

# namespace: placeholder_box

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SpawnPlaceholderBox(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpawnPlaceholderBox()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpawnPlaceholderBox(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SpawnPlaceholderBoxBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x42\x53\x50", size_prefixed=size_prefixed)

    # SpawnPlaceholderBox
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpawnPlaceholderBox
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpawnPlaceholderBox
    def Transform(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from kesko.placeholder_box.Transform import Transform
            obj = Transform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SpawnPlaceholderBox
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from kesko.placeholder_box.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SpawnPlaceholderBoxStart(builder):
    builder.StartObject(3)

def Start(builder):
    SpawnPlaceholderBoxStart(builder)

def SpawnPlaceholderBoxAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    SpawnPlaceholderBoxAddName(builder, name)

def SpawnPlaceholderBoxAddTransform(builder, transform):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(transform), 0)

def AddTransform(builder, transform):
    SpawnPlaceholderBoxAddTransform(builder, transform)

def SpawnPlaceholderBoxAddColor(builder, color):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)

def AddColor(builder, color):
    SpawnPlaceholderBoxAddColor(builder, color)

def SpawnPlaceholderBoxEnd(builder):
    return builder.EndObject()

def End(builder):
    return SpawnPlaceholderBoxEnd(builder)
