# automatically generated by the FlatBuffers compiler, do not modify

# namespace: placeholder_box

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Transform(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 36

    # Transform
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Transform
    def Translation(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Transform
    def Rotation(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj

    # Transform
    def Scale(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj


def CreateTransform(builder, translation_x, translation_y, translation_z, rotation_x, rotation_y, rotation_z, scale_x, scale_y, scale_z):
    builder.Prep(4, 36)
    builder.Prep(4, 12)
    builder.PrependFloat32(scale_z)
    builder.PrependFloat32(scale_y)
    builder.PrependFloat32(scale_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(rotation_z)
    builder.PrependFloat32(rotation_y)
    builder.PrependFloat32(rotation_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(translation_z)
    builder.PrependFloat32(translation_y)
    builder.PrependFloat32(translation_x)
    return builder.Offset()
